hdfs:
  host: localhost
  port: 9000
  path: "/web_logs/"
  user: tpquan

# Kafka configuration
kafka:
  broker_url: localhost:9092
  topic_name: web_logging
  compression_type = "gzip"
  batch_size: 16*1024
  linger_ms: 10
  acks: 1

# Spark configuration
spark:
  master: local[*]
  log_level: WARN
  batch_interval: 10

# HBase configuration
hbase:
  host: localhost
  port: 9090
  table_name: web_logs_summary
  column_family: logs

# Log files configuration
log_files:
  dir_path: /project3/data_processing/log_files/NASA_access_log_Jul95.gz

# Processed data configuration
processed_data:
  dir_path: /project3/data_processing/processed_data