hadoop:
  input_path: /project3/data_processing/hadoop_processing/hadoop_input
  output_path: /project3/data_processing/hadoop_processing/hadoop_output
  log_file_path: /project3/data_processing/log_files/input.log

# Kafka configuration
kafka:
  broker_url: localhost:9092
  topic_name: topic_project3

# Spark configuration
spark:
  master: local[*]
  log_level: WARN
  batch_interval: 10

# HBase configuration
hbase:
  host: localhost
  port: 9090
  table_name: table_project3
