# Kafka configuration
kafka:
  broker_url: localhost:9092
  topic_name: topic_project3

# Spark configuration
spark:
  master: local[*]
  log_level: WARN
  batch_interval: 10

# HBase configuration
hbase:
  host: localhost
  port: 9090
  table_name: table_project3

# Log files configuration
log_files:
  dir_path: /path/to/log/files

# Processed data configuration
processed_data:
  dir_path: /path/to/processed/data
