hdfs:
  host: localhost
  port: 9000
  path: "/web_logs/"
  user: tpquan

# Kafka configuration
kafka:
  broker_url: localhost:9092
  topic_name: web_logging
  compression_type : "gzip"
  batch_size: 16384
  linger_ms: 10
  acks: 1
  buffer_memory: 33554432

# Spark configuration
spark:
  app_name: LogsWebServer
  master: local[*]
  log_level: WARN

# HBase configuration
hbase:
  host: localhost
  port: 9090
  table_name: web_logs_summary
  cf_analysis_results: analysis_results